# Site settings
title: Gabriel Tomé
email: gabrieltomedev@gmail.com
description: "Blog do Gabriel"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://www.gabrieltome.com.br" # the base hostname & protocol for your site
twitter_username: gabrieltdev
github_username:  gabrieltome

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
# permalink: /:year/:month/:day/:title
permalink: /:title
