# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel Tomé
email: gabrieltomedev@gmail.com
description: "Blog do Gabriel"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://www.gabrieltome.com.br" # the base hostname & protocol for your site
twitter_username: gabrieltdev
github_username:  gabrieltome

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
# permalink: /:year/:month/:day/:title
permalink: /:title
